In [37]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math

In [38]:
stocks = pd.read_csv('DOWJONES.csv')
IEX_CLOUD_API_TOKEN = "pk_25bfe6f8656547d0b424e58648030145"

In [39]:
symbol = 'AAPL'
api_url = f"https://cloud.iexapis.com/stable/stock/{symbol}/quote?token={IEX_CLOUD_API_TOKEN}"   #created f string that replaces symbol
#print(api_url)
data = requests.get(api_url).json()   #status == 200 means OK created a json file
# now the data can be used as a dictionary
data

{'symbol': 'AAPL',
 'companyName': 'Apple Inc',
 'primaryExchange': 'NASDAQ/NGS (GLOBAL SELECT MARKET)',
 'calculationPrice': 'close',
 'open': 122.41,
 'openTime': 1607697001653,
 'openSource': 'official',
 'close': 122.41,
 'closeTime': 1607720400935,
 'closeSource': 'official',
 'high': 122.76,
 'highTime': 1607720375404,
 'highSource': '15 minute delayed price',
 'low': 120.55,
 'lowTime': 1607707389120,
 'lowSource': '15 minute delayed price',
 'latestPrice': 122.41,
 'latestSource': 'Close',
 'latestTime': 'December 11, 2020',
 'latestUpdate': 1607720400935,
 'latestVolume': 86939786,
 'iexRealtimePrice': None,
 'iexRealtimeSize': None,
 'iexLastUpdated': None,
 'delayedPrice': 122.35,
 'delayedPriceTime': 1607720375378,
 'oddLotDelayedPrice': 122.345,
 'oddLotDelayedPriceTime': 1607720375238,
 'extendedPrice': 122.27,
 'extendedChange': -0.14,
 'extendedChangePercent': -0.00114,
 'extendedPriceTime': 1607734797513,
 'previousClose': 123.24,
 'previousVolume': 81312170,
 'change': -0.83,
 'changePercent': -0.00673,
 'volume': 86939786,
 'iexMarketPercent': None,
 'iexVolume': None,
 'avgTotalVolume': 92137123,
 'iexBidPrice': None,
 'iexBidSize': None,
 'iexAskPrice': None,
 'iexAskSize': None,
 'iexOpen': 122.41,
 'iexOpenTime': 1607720397799,
 'iexClose': 122.41,
 'iexCloseTime': 1607720397799,
 'marketCap': 2081190582820,
 'peRatio': 37.32,
 'week52High': 133.95,
 'week52Low': 55.74,
 'ytdChange': 0.6750979866838681,
 'lastTradeTime': 1607720397799,
 'isUSMarketOpen': False}

In [40]:
price = data['latestPrice']
market_cap = data['marketCap']
name = data['companyName']

In [41]:
my_columns = ['symbol', 'name', 'price' , 'market cap' , 'shares to buy']
final_dataframe = pd.DataFrame(columns = my_columns)

In [42]:
final_dataframe.append(
    pd.Series(
        [
            symbol,
            name,
            price,
            market_cap,
            'N/A'
        ],
        index = my_columns 
    ),
    ignore_index=True  #it is must dont know why 
)

  symbol       name   price     market cap shares to buy
0   AAPL  Apple Inc  122.41  2081190582820           N/A

In [43]:
for stock in stocks['Ticker']:
    api_url = f"https://cloud.iexapis.com/stable/stock/{stock}/quote?token={IEX_CLOUD_API_TOKEN}"
    data = requests.get(api_url).json()
    price = data['latestPrice']
    name = data['companyName']
    market_cap = data['marketCap']
    
    final_dataframe = final_dataframe.append(
        pd.Series(
            [
                stock,
                name,
                price,
                market_cap,
                'N/A'
            ],
            index = my_columns 
        ),
        ignore_index=True  #it is must dont know why 
    )

In [48]:
amount = float(input("enter amount you want to invest:"))
amount_per_share = amount / len(final_dataframe)
amount_spend=0

enter amount you want to invest:100000

In [49]:
size = len(final_dataframe)
for i in range(size):
    price = final_dataframe.loc[i,'price']
    final_dataframe.loc[i,'shares to buy'] = math.floor(amount_per_share/price)
    amount_spend = amount_spend + final_dataframe.loc[i,'shares to buy'] * price

In [54]:
final_dataframe

,symbol,name,price,market cap,shares to buy
0,AMGN,AMGEN Inc.,227.40,132385142369,15
1,AAPL,Apple Inc,122.41,2081190582820,28
2,BA,Boeing Co.,230.33,130028122576,14
3,CAT,Caterpillar Inc.,179.29,97400777559,19
4,CSCO,"Cisco Systems, Inc.",44.32,187274798252,77
5,CVX,Chevron Corp.,92.45,172634052768,37
6,GS,"Goldman Sachs Group, Inc.",239.99,82572828682,14
7,HD,"Home Depot, Inc.",264.55,284814736614,13
8,HON,Honeywell International Inc,214.63,150602816386,16
9,IBM,International Business Machines Corp.,124.27,110731667805,27
10,INTC,Intel Corp.,49.73,203793540000,69
11,JNJ,Johnson & Johnson,152.95,402647401682,22
12,KO,Coca-Cola Co,53.35,229268136550,64
13,JPM,JPMorgan Chase & Co.,119.56,364443158212,28
14,MCD,McDonald`s Corp,207.76,154804258867,16
15,MMM,3M Co.,174.02,100378543210,19
16,MRK,Merck & Co Inc,82.96,209891656894,41
17,MSFT,Microsoft Corporation,213.26,1612351370349,16
18,NKE,"Nike, Inc. - Class B",137.41,172423343302,25
19,PG,Procter & Gamble Co.,136.51,338491000453,25
20,TRV,Travelers Companies Inc.,134.95,34184017297,25
21,UNH,Unitedhealth Group Inc,337.07,319818996720,10
22,CRM,Salesforce.Com Inc,222.42,203514300000,15
23,VZ,Verizon Communications Inc,60.35,249733995048,57
24,V,Visa Inc - Class A,206.24,441002998600,16
25,WBA,Walgreens Boots Alliance Inc,41.53,35877842460,83
26,WMT,Walmart Inc,147.00,415905031122,23
27,DIS,Walt Disney Co (The),175.72,318138430702,19
28,DOW,Dow Inc,54.00,40054595148,63

In [56]:
print('total amount spend',amount_spend,'out of',amount,'amount left',amount - amount_spend)

total amount spend 98130.9 out of 100000.0 amount left 1869.1000000000058